-- IP_PRODUCT_MAGAZINE_INVENTORY 에 RECEIPT_DATE 컬럼 추가
-- 취소(CANCEL_FLAG='Y') 제외한 가장 최근 입고일 기준
ALTER TABLE IP_PRODUCT_MAGAZINE_INVENTORY ADD (RECEIPT_DATE DATE);

UPDATE IP_PRODUCT_MAGAZINE_INVENTORY INV
   SET RECEIPT_DATE = (
         SELECT MAX(R.RECEIPT_DATE)
           FROM IP_PRODUCT_MAGAZINE_RECEIPT R
          WHERE R.MAGAZINE_NO  = INV.MAGAZINE_NO
            AND NVL(R.CANCEL_FLAG, 'N') = 'N'
       );

COMMIT;
