-- IP_PRODUCT_LINE_TARGET 테이블에 모델/리더 관련 컬럼 추가
-- 생산계획등록(메뉴 20) 및 투입/포장 모니터링(메뉴 22, 23)에서 사용
ALTER TABLE IP_PRODUCT_LINE_TARGET ADD (
  MODEL_NAME     VARCHAR2(50),
  ITEM_CODE      VARCHAR2(20),
  UPH            NUMBER,
  LEADER_ID      VARCHAR2(20),
  SUB_LEADER_ID  VARCHAR2(20)
);

COMMENT ON COLUMN IP_PRODUCT_LINE_TARGET.MODEL_NAME IS '모델명';
COMMENT ON COLUMN IP_PRODUCT_LINE_TARGET.ITEM_CODE IS '제품코드';
COMMENT ON COLUMN IP_PRODUCT_LINE_TARGET.UPH IS '시간당 생산능력';
COMMENT ON COLUMN IP_PRODUCT_LINE_TARGET.LEADER_ID IS '리더 사번 (ISYS_USERS.USER_ID)';
COMMENT ON COLUMN IP_PRODUCT_LINE_TARGET.SUB_LEADER_ID IS '부리더 사번 (ISYS_USERS.USER_ID)';
