--------------------------------------------------------------------------------
-- IQ_ANORMAL_CODE : CTQ 이상점 마스터 코드
-- 품종 + 항목 + 기준 + 등급 + 발생공정 + Master Code 조합 관리
--
-- PK 설계 근거:
--   Master Code 는 [품종][카테고리][0][등급][공정] 의 4자리 축약 조합 식별자라
--   세부 기준이 달라도 동일 코드가 나올 수 있음 (예: AC0BA 는 원자재/B등급/ICT
--   조합인 "동일부품 불량 3건/90일" 과 "공용부품 Open/Short 2건/일" 에 공통 부여).
--   따라서 비즈니스 키 MASTER_CODE 는 UNIQUE 로 걸 수 없고, 일련번호 SEQ 를 PK 로 둔다.
--------------------------------------------------------------------------------

CREATE TABLE IQ_ANORMAL_CODE (
    SEQ              NUMBER(10)       NOT NULL,
    PRODUCT_TYPE     VARCHAR2(50)     NOT NULL,
    CATEGORY         VARCHAR2(50)     NOT NULL,
    CRITERIA         VARCHAR2(200)    NOT NULL,
    GRADE            VARCHAR2(10),
    PROCESS_NAME     VARCHAR2(50),
    MASTER_CODE      VARCHAR2(20),
    ENTER_DATE       DATE,
    ENTER_BY         VARCHAR2(30),
    LAST_MODIFY_DATE DATE,
    LAST_MODIFY_BY   VARCHAR2(30),
    ORGANIZATION_ID  NUMBER,
    CONSTRAINT PK_IQ_ANORMAL_CODE PRIMARY KEY (SEQ)
)
/

CREATE SEQUENCE SEQ_IQ_ANORMAL_CODE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE INDEX IX_IQ_ANORMAL_CODE_01 ON IQ_ANORMAL_CODE (MASTER_CODE)
/

BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE IQ_ANORMAL_CODE IS 'CTQ 이상점 마스터 코드 (품종+항목+기준+등급+공정+마스터코드)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.SEQ IS '일련번호 (PK, SEQ_IQ_ANORMAL_CODE.NEXTVAL)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.PRODUCT_TYPE IS '품종 (예: SMPS, 공통)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.CATEGORY IS '항목 (반복성/사고성/원자재/지표/설비/미발생)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.CRITERIA IS '이상점 기준 상세 설명']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.GRADE IS '등급 (A등급/B등급/C등급/등급무)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.PROCESS_NAME IS '발생공정 (ICT/Hi-Pot/FT/Burn-In/ATE/통합공정/공정무)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.MASTER_CODE IS '마스터 코드 (품종+카테고리+0+등급+공정 조합 식별자, 중복 가능)']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.ENTER_DATE IS '등록일시']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.ENTER_BY IS '등록자']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.LAST_MODIFY_DATE IS '최종수정일시']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.LAST_MODIFY_BY IS '최종수정자']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN IQ_ANORMAL_CODE.ORGANIZATION_ID IS '조직 ID (다중 법인 대응)']';
END;
/

BEGIN
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '반복성', '동일불량 연속발생 (2건 연속)', 'A등급', 'FT',         'AA0AC', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '반복성', '동일불량 연속발생 (2건 연속)', 'A등급', 'ATE',        'AA0AE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '반복성', '동일불량 발생 (2건/일)',       'B등급', 'FT',         'AA0BC', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '반복성', '동일불량 발생 (2건/일)',       'B등급', 'ATE',        'AA0BE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '사고성', 'Hi-Pot 불량 (1건/일)',         'A등급', 'Hi-Pot',     'AB0AB', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '사고성', 'Burn-In불량 (1건/일)',         'B등급', 'Burn-In',    'AB0BD', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '사고성', '규격 불량 (1건/일)',           'B등급', 'ATE',        'AB0BE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '사고성', 'Burn-In불량 (2건/일)',         'A등급', 'Burn-In',    'AB0AD', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '사고성', '규격 불량 (2건/일)',           'A등급', 'ATE',        'AB0AE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/일)',       'A등급', 'ICT',        'AC0AA', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/일)',       'A등급', 'Hi-Pot',     'AC0AB', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/일)',       'A등급', 'FT',         'AC0AC', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/일)',       'A등급', 'Burn-In',    'AC0AD', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/일)',       'A등급', 'ATE',        'AC0AE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/90일)',     'B등급', 'ICT',        'AC0BA', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/90일)',     'B등급', 'Hi-Pot',     'AC0BB', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/90일)',     'B등급', 'FT',         'AC0BC', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/90일)',     'B등급', 'Burn-In',    'AC0BD', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '동일부품 불량 (3건/90일)',     'B등급', 'ATE',        'AC0BE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '원자재', '공용부품 Open/Short (2건/일)', 'B등급', 'ICT',        'AC0BA', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '불량률 증가 (전주대비 2배)',   'C등급', 'ICT',        'AD0CA', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '불량률 증가 (전주대비 2배)',   'C등급', 'Hi-Pot',     'AD0CB', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '불량률 증가 (전주대비 2배)',   'C등급', 'FT',         'AD0CC', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '불량률 증가 (전주대비 2배)',   'C등급', 'Burn-In',    'AD0CD', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '불량률 증가 (전주대비 2배)',   'C등급', 'ATE',        'AD0CE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '불량률 증가 (전월대비 2배)',   'C등급', '통합공정',   'AD0CH', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '공정 직행률 (누적수율 90%이하)', 'A등급', 'Hi-Pot',     'AD0AB', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '공정 직행률 (누적수율 90%이하)', 'A등급', 'FT',         'AD0AC', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '공정 직행률 (누적수율 90%이하)', 'A등급', 'Burn-In',    'AD0AD', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '지표',   '공정 직행률 (누적수율 90%이하)', 'A등급', 'ATE',        'AD0AE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '설비',   '설비 이상 및 정지 (60분 이상)', 'C등급', 'ICT',        'AE0CA', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '설비',   '설비 이상 및 정지 (60분 이상)', 'C등급', 'Hi-Pot',     'AE0CB', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '설비',   '설비 이상 및 정지 (60분 이상)', 'C등급', 'FT',         'AE0CC', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '설비',   '설비 이상 및 정지 (60분 이상)', 'C등급', 'Burn-In',    'AE0CD', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, 'SMPS', '설비',   '설비 이상 및 정지 (60분 이상)', 'C등급', 'ATE',        'AE0CE', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  INSERT INTO IQ_ANORMAL_CODE (SEQ, PRODUCT_TYPE, CATEGORY, CRITERIA, GRADE, PROCESS_NAME, MASTER_CODE, ENTER_DATE, ENTER_BY, LAST_MODIFY_DATE, LAST_MODIFY_BY) VALUES (SEQ_IQ_ANORMAL_CODE.NEXTVAL, '공통',  '미발생', '이상점 미발생',                 '등급무', '공정무',     'ZZZZZZ', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
  COMMIT;
END;
/
