-- ============================================================
-- LOG 테이블 IS_LAST 트리거 수정 — 불량 시 자동 QC 등록 추가
-- 기존 IS_LAST 로직 유지 + FAIL 시 P_AUTO_INSERT_QC 호출
--
-- 컬럼 매핑:
--   BARCODE 대체: LOG_AOI/LOG_MAOI → SERIAL_NO
--                 LOG_COATINGVISION → MAIN_BARCODE
--                 LOG_SPI → MASTER_BARCODE
--   RESULT 대체:  LOG_EOL → ARRAY_RESULT
--                 LOG_LOWCURRENT → OVERALL_RESULT
--                 LOG_SPI → PCB_RESULT
--                 LOG_VISION_LEGACY → DEVICE_RESULT
-- ============================================================

-- 1. LOG_AOI → W070 (SAOI) — BARCODE=SERIAL_NO
CREATE OR REPLACE TRIGGER TRG_LOG_AOI_IS_LAST
BEFORE INSERT ON LOG_AOI
FOR EACH ROW
BEGIN
  UPDATE LOG_AOI
  SET IS_LAST = 'N'
  WHERE SERIAL_NO = :NEW.SERIAL_NO
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.SERIAL_NO, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W070');
  END IF;
END;
/

-- 2. LOG_COATING1 → W120 (COATING 1)
CREATE OR REPLACE TRIGGER TRG_LOG_COATING1_IS_LAST
BEFORE INSERT ON LOG_COATING1
FOR EACH ROW
BEGIN
  UPDATE LOG_COATING1
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W120');
  END IF;
END;
/

-- 3. LOG_COATING2 → W121 (COATING 2)
CREATE OR REPLACE TRIGGER TRG_LOG_COATING2_IS_LAST
BEFORE INSERT ON LOG_COATING2
FOR EACH ROW
BEGIN
  UPDATE LOG_COATING2
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W121');
  END IF;
END;
/

-- 4. LOG_COATINGVISION → W122 (COATING V) — BARCODE=MAIN_BARCODE
CREATE OR REPLACE TRIGGER TRG_LOG_COATINGVISION_IS_LAST
BEFORE INSERT ON LOG_COATINGVISION
FOR EACH ROW
BEGIN
  UPDATE LOG_COATINGVISION
  SET IS_LAST = 'N'
  WHERE MAIN_BARCODE = :NEW.MAIN_BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.MAIN_BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W122');
  END IF;
END;
/

-- 5. LOG_DOWNLOAD → W130 (DOWNLOAD)
CREATE OR REPLACE TRIGGER TRG_LOG_DOWNLOAD_IS_LAST
BEFORE INSERT ON LOG_DOWNLOAD
FOR EACH ROW
BEGIN
  UPDATE LOG_DOWNLOAD
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W130');
  END IF;
END;
/

-- 6. LOG_EOL → W155 (EOL FCT) — RESULT=ARRAY_RESULT
CREATE OR REPLACE TRIGGER TRG_LOG_EOL_IS_LAST
BEFORE INSERT ON LOG_EOL
FOR EACH ROW
BEGIN
  UPDATE LOG_EOL
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.ARRAY_RESULT IS NOT NULL
     AND UPPER(:NEW.ARRAY_RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W155');
  END IF;
END;
/

-- 7. LOG_FCT → W135 (FCT)
CREATE OR REPLACE TRIGGER TRG_LOG_FCT_IS_LAST
BEFORE INSERT ON LOG_FCT
FOR EACH ROW
BEGIN
  UPDATE LOG_FCT
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W135');
  END IF;
END;
/

-- 8. LOG_ICT → W110 (ICT)
CREATE OR REPLACE TRIGGER TRG_LOG_ICT_IS_LAST
BEFORE INSERT ON LOG_ICT
FOR EACH ROW
BEGIN
  UPDATE LOG_ICT
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W110');
  END IF;
END;
/

-- 9. LOG_LOWCURRENT → W145 (LOW CURRENT) — RESULT=OVERALL_RESULT
CREATE OR REPLACE TRIGGER TRG_LOG_LOWCURRENT_IS_LAST
BEFORE INSERT ON LOG_LOWCURRENT
FOR EACH ROW
BEGIN
  UPDATE LOG_LOWCURRENT
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.OVERALL_RESULT IS NOT NULL
     AND UPPER(:NEW.OVERALL_RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W145');
  END IF;
END;
/

-- 10. LOG_MAOI → W060 (MAOI) — BARCODE=SERIAL_NO
CREATE OR REPLACE TRIGGER TRG_LOG_MAOI_IS_LAST
BEFORE INSERT ON LOG_MAOI
FOR EACH ROW
BEGIN
  UPDATE LOG_MAOI
  SET IS_LAST = 'N'
  WHERE SERIAL_NO = :NEW.SERIAL_NO
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.SERIAL_NO, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W060');
  END IF;
END;
/

-- 11. LOG_SPI → W030 (SPI) — BARCODE=MASTER_BARCODE, RESULT=PCB_RESULT
CREATE OR REPLACE TRIGGER TRG_LOG_SPI_IS_LAST
BEFORE INSERT ON LOG_SPI
FOR EACH ROW
BEGIN
  UPDATE LOG_SPI
  SET IS_LAST = 'N'
  WHERE MASTER_BARCODE = :NEW.MASTER_BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.PCB_RESULT IS NOT NULL
     AND UPPER(:NEW.PCB_RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.MASTER_BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W030');
  END IF;
END;
/

-- 12. LOG_VISION_LEGACY → W150 (VISION TEST) — RESULT=DEVICE_RESULT
CREATE OR REPLACE TRIGGER TRG_LOG_VISION_LEGACY_IS_LAST
BEFORE INSERT ON LOG_VISION_LEGACY
FOR EACH ROW
BEGIN
  UPDATE LOG_VISION_LEGACY
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.DEVICE_RESULT IS NOT NULL
     AND UPPER(:NEW.DEVICE_RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W150');
  END IF;
END;
/

-- 13. LOG_VISION_NATIVE → W150 (VISION TEST)
CREATE OR REPLACE TRIGGER TRG_LOG_VISION_NATIVE_IS_LAST
BEFORE INSERT ON LOG_VISION_NATIVE
FOR EACH ROW
BEGIN
  UPDATE LOG_VISION_NATIVE
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.RESULT IS NOT NULL
     AND UPPER(:NEW.RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W150');
  END IF;
END;
/
