-- IP_PRODUCT_WORK_QC 테이블 컬럼 주석 업데이트
-- 코드값 정보 ISYS_BASECODE에서 조회하여 기존 주석에 추가

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.BAD_CAUSE_BY IS '불량사유처 (코드: A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,R,S)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.BAD_PHENOMENON IS '불량현상 (코드: ATV,AUDIO LOOPBACK,AX POWER ON,BAD ASSEMBLY,BLE CHECK,Cam,CH Setting,COMP/AV LOOPBACK,COSMETICO,DRM,DTV,EEPROM,ETC,FACTORY,Frequency left,Frequency right,HDMI CRC,HDMI SST,HDMI Frequency1_left,HDMI Frequency2_right,IDS_INSPECTION,ILLUMINANCE,IRB,KEY INSPECTION,LAN,MODEL OPTION,NDF,NO IMAGEN,OTP ver,Panel type,PMIC CHECK,RF INSPECTION,SOC IC TEMPERATURA,SOUND,SPDIF,SWITCH CHECK,Tuner_connection_check,TV_MODE CHANGE,USB,VERSI온,VISUAL,VOLTAGE,WIFI,Wachdog)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.BAD_REASON_CODE IS '불량원인 (코드: A,B,C,D)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.LINE_CODE IS '라인코드 (코드: 01,02,03,04,05,06,07,08,09,10,11,12,13,14,15)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.LOCATION_CODE IS '로케이션(위치) (코드: M01,M02,M03,M04,M05,M06,M07,M99)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.QC_INSPECT_HANDLING IS '후처리 (코드: B,D,S,U,W)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.QC_RESULT IS '진가성 (코드: N,O,W)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.RECEIPT_DEFICIT IS '입출구분 (코드: 1,2)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.REPAIR_RESULT_CODE IS '수리결과 (코드: G,N)';

COMMENT ON COLUMN IP_PRODUCT_WORK_QC.SHIFT_CODE IS '교대조 (코드: A,B,C)';
