-- =========================================================================
-- 001_ai_chat_tables.sql
-- AI 챗 (MES 도메인 어시스턴트) 신규 테이블 5개 + 시드
-- 실행 환경: 메인 DB 사용자 (config/database.json activeProfile 계정)
-- 주의: oracle_connector.py --execute-file 는 "/" 한 줄로 블록을 분리함.
-- =========================================================================

-- 세션 헤더
CREATE TABLE AI_CHAT_SESSION (
  SESSION_ID       VARCHAR2(40)  PRIMARY KEY,
  TITLE            VARCHAR2(200) NOT NULL,
  PROVIDER_ID      VARCHAR2(20),
  MODEL_ID         VARCHAR2(80),
  PERSONA_ID       VARCHAR2(40),
  CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  LAST_MESSAGE_AT  TIMESTAMP,
  MESSAGE_COUNT    NUMBER DEFAULT 0
)
/

CREATE INDEX IX_AI_CHAT_SESSION_LAST ON AI_CHAT_SESSION(LAST_MESSAGE_AT DESC)
/

-- 메시지 본문
CREATE TABLE AI_CHAT_MESSAGE (
  MESSAGE_ID       VARCHAR2(40)  PRIMARY KEY,
  SESSION_ID       VARCHAR2(40)  NOT NULL REFERENCES AI_CHAT_SESSION(SESSION_ID) ON DELETE CASCADE,
  ROLE             VARCHAR2(20)  NOT NULL,
  CONTENT          CLOB,
  SQL_TEXT         CLOB,
  RESULT_JSON      CLOB,
  TOKENS_IN        NUMBER,
  TOKENS_OUT       NUMBER,
  EXEC_MS          NUMBER,
  CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
/

CREATE INDEX IX_AI_CHAT_MESSAGE_SESSION ON AI_CHAT_MESSAGE(SESSION_ID, CREATED_AT)
/

-- 페르소나
CREATE TABLE AI_PERSONA (
  PERSONA_ID      VARCHAR2(40)  PRIMARY KEY,
  NAME            VARCHAR2(80)  NOT NULL,
  DESCRIPTION     VARCHAR2(300),
  ICON            VARCHAR2(40),
  SYSTEM_PROMPT   CLOB          NOT NULL,
  IS_DEFAULT      NUMBER(1) DEFAULT 0,
  IS_ACTIVE       NUMBER(1) DEFAULT 1,
  SORT_ORDER      NUMBER DEFAULT 0,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP
)
/

-- 프로바이더 설정
CREATE TABLE AI_PROVIDER_SETTING (
  PROVIDER_ID         VARCHAR2(20)  PRIMARY KEY,
  ENABLED             NUMBER(1) DEFAULT 0,
  API_KEY_ENC         VARCHAR2(500),
  DEFAULT_MODEL_ID    VARCHAR2(80),
  SQL_SYSTEM_PROMPT   CLOB,
  ANALYSIS_PROMPT     CLOB,
  UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
/

-- 동적 용어 사전
CREATE TABLE AI_GLOSSARY_TERM (
  TERM_ID         VARCHAR2(40)  PRIMARY KEY,
  CATEGORY        VARCHAR2(40)  NOT NULL,
  TERM            VARCHAR2(120) NOT NULL,
  DEFINITION      CLOB          NOT NULL,
  EXAMPLE_SQL     CLOB,
  PRIORITY        NUMBER DEFAULT 0,
  IS_ACTIVE       NUMBER(1) DEFAULT 1,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP
)
/

CREATE INDEX IX_AI_GLOSSARY_CAT ON AI_GLOSSARY_TERM(CATEGORY, PRIORITY DESC)
/

-- ===== 시드 데이터 =====

-- 페르소나 3종 (IS_DEFAULT=1 하나만, 나머지 0)
INSERT INTO AI_PERSONA (PERSONA_ID,NAME,DESCRIPTION,ICON,SYSTEM_PROMPT,IS_DEFAULT,IS_ACTIVE,SORT_ORDER,CREATED_AT,UPDATED_AT) VALUES
('p_default','MES 분석가','데이터를 객관적으로 요약·해석','BarChart3',
 '당신은 MES 데이터 분석가입니다. 결과를 표/차트 중심으로 객관적으로 요약하고 이상치를 강조하세요. 감정·장식 표현을 줄이고 숫자와 비율로 말하세요.',
 1,1,0,SYSTIMESTAMP,NULL)
/

INSERT INTO AI_PERSONA (PERSONA_ID,NAME,DESCRIPTION,ICON,SYSTEM_PROMPT,IS_DEFAULT,IS_ACTIVE,SORT_ORDER,CREATED_AT,UPDATED_AT) VALUES
('p_manager','라인 매니저','의사결정에 직접 쓸 수 있는 인사이트','ClipboardCheck',
 '당신은 라인 매니저를 보좌하는 어시스턴트입니다. 각 응답 끝에 "조치 제안"을 1~3개 bullet로 제공하세요. 통계 용어 대신 현장 용어를 사용하세요.',
 0,1,1,SYSTIMESTAMP,NULL)
/

INSERT INTO AI_PERSONA (PERSONA_ID,NAME,DESCRIPTION,ICON,SYSTEM_PROMPT,IS_DEFAULT,IS_ACTIVE,SORT_ORDER,CREATED_AT,UPDATED_AT) VALUES
('p_quality','품질 엔지니어','FPY/SPC/이상점 중심의 품질 관점','ShieldCheck',
 '당신은 품질 엔지니어 관점으로 응답합니다. FPY·CTQ·SPC 이상점·MSL 경고에 우선순위를 두고, 통계적 유의성과 시간 추이에 주목하세요.',
 0,1,2,SYSTIMESTAMP,NULL)
/

-- 글로서리 5종
INSERT INTO AI_GLOSSARY_TERM (TERM_ID,CATEGORY,TERM,DEFINITION,EXAMPLE_SQL,PRIORITY,IS_ACTIVE,CREATED_AT,UPDATED_AT) VALUES
('g_p51','code','P51','SMPS-1 라인. 베트남 SMPS 1호기.',NULL,100,1,SYSTIMESTAMP,NULL)
/

INSERT INTO AI_GLOSSARY_TERM (TERM_ID,CATEGORY,TERM,DEFINITION,EXAMPLE_SQL,PRIORITY,IS_ACTIVE,CREATED_AT,UPDATED_AT) VALUES
('g_w220','code','W220','포장 공정 코드. IP_PRODUCT_WORKSTAGE_IO.WORKSTAGE_CODE 컬럼.',NULL,100,1,SYSTIMESTAMP,NULL)
/

INSERT INTO AI_GLOSSARY_TERM (TERM_ID,CATEGORY,TERM,DEFINITION,EXAMPLE_SQL,PRIORITY,IS_ACTIVE,CREATED_AT,UPDATED_AT) VALUES
('g_w310','code','W310','투입 공정 코드.',NULL,100,1,SYSTIMESTAMP,NULL)
/

INSERT INTO AI_GLOSSARY_TERM (TERM_ID,CATEGORY,TERM,DEFINITION,EXAMPLE_SQL,PRIORITY,IS_ACTIVE,CREATED_AT,UPDATED_AT) VALUES
('g_uph','abbreviation','UPH','Units Per Hour. 시간당 생산수량 목표.',NULL,50,1,SYSTIMESTAMP,NULL)
/

INSERT INTO AI_GLOSSARY_TERM (TERM_ID,CATEGORY,TERM,DEFINITION,EXAMPLE_SQL,PRIORITY,IS_ACTIVE,CREATED_AT,UPDATED_AT) VALUES
('g_eol','abbreviation','EOL','End Of Line 검사 — 생산 라인 마지막 단계.',NULL,50,1,SYSTIMESTAMP,NULL)
/

-- 프로바이더 4행 (ENABLED=0 시작)
INSERT INTO AI_PROVIDER_SETTING (PROVIDER_ID,ENABLED,DEFAULT_MODEL_ID,UPDATED_AT) VALUES ('claude',0,'claude-opus-4-6',SYSTIMESTAMP)
/

INSERT INTO AI_PROVIDER_SETTING (PROVIDER_ID,ENABLED,DEFAULT_MODEL_ID,UPDATED_AT) VALUES ('gemini',0,'gemini-2.0-flash',SYSTIMESTAMP)
/

INSERT INTO AI_PROVIDER_SETTING (PROVIDER_ID,ENABLED,DEFAULT_MODEL_ID,UPDATED_AT) VALUES ('mistral',0,'mistral-large-latest',SYSTIMESTAMP)
/

INSERT INTO AI_PROVIDER_SETTING (PROVIDER_ID,ENABLED,DEFAULT_MODEL_ID,UPDATED_AT) VALUES ('kimi',0,'kimi-k2-0905-preview',SYSTIMESTAMP)
/

COMMIT
/
