-- migrations/002_ai_chat_feedback.sql
-- AI 챗 피드백 테이블 + 메시지 성능 컬럼 추가
-- 실행: oracle_connector.py --execute-file migrations/002_ai_chat_feedback.sql --site SVEHICLEPDB

-- AI_CHAT_MESSAGE에 성능 측정 컬럼 추가 (이미 있으면 무시)
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE AI_CHAT_MESSAGE ADD (SQL_GEN_MS NUMBER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE AI_CHAT_MESSAGE ADD (SQL_EXEC_MS NUMBER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE AI_CHAT_MESSAGE ADD (ANALYSIS_MS NUMBER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- 피드백 테이블
CREATE TABLE AI_CHAT_FEEDBACK (
  FEEDBACK_ID      VARCHAR2(40)  PRIMARY KEY,
  MESSAGE_ID       VARCHAR2(40)  NOT NULL,
  SESSION_ID       VARCHAR2(40)  NOT NULL,
  RATING           VARCHAR2(10)  NOT NULL,
  USER_QUERY       CLOB,
  LLM_RESPONSE     CLOB,
  SQL_QUERY        CLOB,
  RESULT_JSON      CLOB,
  PROVIDER_ID      VARCHAR2(20),
  MODEL_ID         VARCHAR2(80),
  TOTAL_MS         NUMBER,
  SQL_GEN_MS       NUMBER,
  SQL_EXEC_MS      NUMBER,
  ANALYSIS_MS      NUMBER,
  CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP
)
/

CREATE INDEX IX_AI_FEEDBACK_CREATED ON AI_CHAT_FEEDBACK(CREATED_AT DESC)
/
CREATE INDEX IX_AI_FEEDBACK_RATING ON AI_CHAT_FEEDBACK(RATING)
/
CREATE INDEX IX_AI_FEEDBACK_SESSION ON AI_CHAT_FEEDBACK(SESSION_ID)
/

COMMIT
/
