#!/usr/bin/env python3
import subprocess
import json

# IP* 테이블 (생산 관련 주요 테이블)
tables = [
    'IP_ASSEMBLY_ISSUE', 'IP_ASSEMBLY_RESULT', 'IP_ASSEMBLY_RESULT_BARCODE', 'IP_ASSEMBLY_RESULT_HISTORY',
    'IP_LABEL_MASTER', 'IP_LINE_DAILY_OPERATION', 'IP_LINE_DAILY_OPERATION_HIST', 'IP_LINE_IDLE_TIME',
    'IP_MACHINE_DAILY_OPERATION', 'IP_MACHINE_INSPECT_MCN_STATUS', 'IP_PRODUCT_2D_BARCODE',
    'IP_PRODUCT_2D_BARCODE_DEL', 'IP_PRODUCT_2D_BARCODE_PAIR', 'IP_PRODUCT_BARCODE_EXTERNAL',
    'IP_PRODUCT_CARRIER_BARCODE', 'IP_PRODUCT_COMPANY_CALENDAR', 'IP_PRODUCT_DAILY_LINE_CAPACITY',
    'IP_PRODUCT_DAILY_MCN_CAPACITY', 'IP_PRODUCT_DAILY_RESULT', 'IP_PRODUCT_DAILY_WS_CAPACITY',
    'IP_PRODUCT_DEFECT', 'IP_PRODUCT_DELIVERY_MONTH_PLAN', 'IP_PRODUCT_DELIVERY_PLAN',
    'IP_PRODUCT_FG_INVENTORY', 'IP_PRODUCT_FG_ISSUE', 'IP_PRODUCT_FG_PALLET', 'IP_PRODUCT_FG_RECEIPT',
    'IP_PRODUCT_FT_DAILY_RESULTS', 'IP_PRODUCT_INV_4_REQUIREMENT', 'IP_PRODUCT_ISSUE_PID_SCAN',
    'IP_PRODUCT_LASER_MARKING', 'IP_PRODUCT_LINE', 'IP_PRODUCT_LINE_BARCODE', 'IP_PRODUCT_LINE_CALENDAR',
    'IP_PRODUCT_LINE_CAPACITY', 'IP_PRODUCT_LINE_RESULT', 'IP_PRODUCT_LINE_TARGET', 'IP_PRODUCT_MAGAZINE',
    'IP_PRODUCT_MAGAZINE_HIS', 'IP_PRODUCT_MAGAZINE_MASTER', 'IP_PRODUCT_MAINFLASH_VERSION',
    'IP_PRODUCT_MAOI_DAILY_RESULTS', 'IP_PRODUCT_MCN_CALENDAR', 'IP_PRODUCT_MI_MONTH_PLAN',
    'IP_PRODUCT_MI_PLAN', 'IP_PRODUCT_MOBILIZATION', 'IP_PRODUCT_MODEL_MASTER',
    'IP_PRODUCT_MODEL_MASTER_ATTRIBUTES', 'IP_PRODUCT_MODEL_MASTER_FWDN', 'IP_PRODUCT_MODEL_MASTER_FWDN_HIS',
    'IP_PRODUCT_MODEL_MASTER_MD_MODEL', 'IP_PRODUCT_MODEL_MICOM_HISOTRY', 'IP_PRODUCT_MODEL_ST_MASTER',
    'IP_PRODUCT_MOLD_CALENDAR', 'IP_PRODUCT_OEMBOX_MASTER', 'IP_PRODUCT_PACK_ASSY_MASTER',
    'IP_PRODUCT_PACK_MASTER', 'IP_PRODUCT_PACK_MASTER_DEL', 'IP_PRODUCT_PACK_SERIAL',
    'IP_PRODUCT_PACK_SERIAL_DEL', 'IP_PRODUCT_PCB_SCAN_MASTER', 'IP_PRODUCT_PDA_SCAN_MASTER',
    'IP_PRODUCT_PIDCHECK_HISTORY', 'IP_PRODUCT_REINPUT_RESULT', 'IP_PRODUCT_REPAIR',
    'IP_PRODUCT_RESULT', 'IP_PRODUCT_RESULT_BARCODE', 'IP_PRODUCT_RESULT_HISTORY',
    'IP_PRODUCT_REWORK_RESULT', 'IP_PRODUCT_ROUTING', 'IP_PRODUCT_ROUTING_MASTER', 'IP_PRODUCT_ROUTING_MODEL',
    'IP_PRODUCT_RUNNING_HIST', 'IP_PRODUCT_RUN_CARD', 'IP_PRODUCT_RUN_CARD_CLOSE', 'IP_PRODUCT_RUN_CARD_DEL',
    'IP_PRODUCT_RUN_CARD_DETAIL', 'IP_PRODUCT_RUN_CARD_INV', 'IP_PRODUCT_RUN_CARD_IO',
    'IP_PRODUCT_RUN_CARD_IO_BACK', 'IP_PRODUCT_RUN_MODEL', 'IP_PRODUCT_RUN_MODEL_LOG',
    'IP_PRODUCT_SAOI_DAILY_RESULTS', 'IP_PRODUCT_SCAN_HISTORY', 'IP_PRODUCT_SCAN_INPUT_HISTORY',
    'IP_PRODUCT_SCAN_MAPPING_HISTORY', 'IP_PRODUCT_SCAN_MAPPING_HIST_DEL', 'IP_PRODUCT_SCAN_MAPPING_KTC',
    'IP_PRODUCT_SELECTION_DATA_TEMP', 'IP_PRODUCT_SENSOR_ACTUAL', 'IP_PRODUCT_SENSOR_ACTUAL_BACK',
    'IP_PRODUCT_SENSOR_ACTUAL_HOUR', 'IP_PRODUCT_SENSOR_ACTUAL_RUNNO', 'IP_PRODUCT_SENSOR_ACTUAL_TIME',
    'IP_PRODUCT_SERIAL_RESULT', 'IP_PRODUCT_SHIFT_RESULT', 'IP_PRODUCT_SMD_MONTH_PLAN',
    'IP_PRODUCT_SMD_PLAN', 'IP_PRODUCT_SMD_PLAN_ISSUE', 'IP_PRODUCT_SOFTWARE_EXCEL',
    'IP_PRODUCT_SOFTWARE_MASTER', 'IP_PRODUCT_SPEC_CONFIRM_DOC', 'IP_PRODUCT_SPI_DAILY_RESULTS',
    'IP_PRODUCT_SSCD_DATA_CHECK', 'IP_PRODUCT_ST', 'IP_PRODUCT_WORKORDER_DOCUMENT',
    'IP_PRODUCT_WORKSTAGE', 'IP_PRODUCT_WORKSTAGE_INV', 'IP_PRODUCT_WORKSTAGE_IO',
    'IP_PRODUCT_WORKSTAGE_IO_DEL', 'IP_PRODUCT_WORKSTAGE_JIG', 'IP_PRODUCT_WORKSTAGE_PACK',
    'IP_PRODUCT_WORKSTAGE_RESULT', 'IP_PRODUCT_WORK_QC', 'IP_PRODUCT_WORK_QC_EXCEL',
    'IP_PRODUCT_WORK_QC_IMAGE', 'IP_PRODUCT_WORK_QC_REPAIR_ITEM', 'IP_PRODUCT_WORK_TIME',
    'IP_PRODUCT_WRONG_COMPONENT', 'IP_PRODUCT_WRONG_RETURN_PID', 'IP_PRODUCT_WS_CALENDAR',
    'IP_PRODUCT_WS_CAPACITY', 'IP_PRODUCT_YEAR_BASE', 'IP_SHIFT_TIME_MASTER', 'IP_SMT_MARKING_LOG'
]

total_updated = 0
total_tables = 0
for table in tables:
    result = subprocess.run(
        ['python', 'C:/Users/hsyou/.claude/skills/oracle-db/scripts/add_code_comments.py', table, '--site', 'SVEHICLEPDB'],
        capture_output=True, text=True
    )
    try:
        data = json.loads(result.stdout)
        if data['success'] and data['updated']:
            print(f'{table}: {len(data["updated"])}개 컬럼 업데이트')
            total_updated += len(data['updated'])
            total_tables += 1
    except Exception as e:
        print(f'{table}: 오류 - {e}')

print(f'\nIP* 테이블: {total_tables}개 테이블, 총 {total_updated}개 컬럼 업데이트 완료')
