#!/usr/bin/env python3
import subprocess
import json

# IQ* 테이블 (품질 관련 주요 테이블)
tables = [
    'IQC_INSPECTION_TEMPLATE', 'IQC_INSPECTION_TIME_CHECK', 'IQ_4M_MASTER',
    'IQ_CHECK_FOOLPROOF_HISTORY', 'IQ_DAILY_DASHBOARD', 'IQ_DAILY_NOTIFY',
    'IQ_INSPECT_MASTER_SAMPLE_LOG', 'IQ_INSPECT_MAXPOWER_SPEC', 'IQ_INTERLOCK_CHECK_CONDITION',
    'IQ_INTERLOCK_CHECK_COND_LOG', 'IQ_INTERLOCK_CHECK_ERROR', 'IQ_INTERLOCK_CHECK_RESULT',
    'IQ_INTERLOCK_CHECK_RESULT_SUM', 'IQ_INTERLOCK_REFLOW_DATA', 'IQ_INTERLOCK_REFLOW_STATUS',
    'IQ_INTERLOCK_REQUEST_LOG', 'IQ_IQC_DOCUMENT', 'IQ_IQC_INSPECT_HISTORY',
    'IQ_ITEM_EQUIPMENT_DETAIL', 'IQ_ITEM_INSPECT_GROUP', 'IQ_ITEM_IQC', 'IQ_ITEM_IQC_BAD',
    'IQ_ITEM_IQC_CRITERION', 'IQ_ITEM_IQC_RANGE', 'IQ_ITEM_OQC_CRITERION',
    'IQ_LED_INSPECT_CONDITION', 'IQ_MACHINE_DATA_RAW', 'IQ_MACHINE_FT_HA_DATA_RAW',
    'IQ_MACHINE_ICT_DTL_HA_DATA_RAW', 'IQ_MACHINE_ICT_HA_DATA_RAW',
    'IQ_MACHINE_INPSECT_DATA_FEEDERCHECK', 'IQ_MACHINE_INSPECT_BOARD_EVENT',
    'IQ_MACHINE_INSPECT_DATA_ACTUAL_MM', 'IQ_MACHINE_INSPECT_DATA_AGING',
    'IQ_MACHINE_INSPECT_DATA_AOI', 'IQ_MACHINE_INSPECT_DATA_AOI_DFT', 'IQ_MACHINE_INSPECT_DATA_AOI_NG',
    'IQ_MACHINE_INSPECT_DATA_AOI_TEST', 'IQ_MACHINE_INSPECT_DATA_ICT', 'IQ_MACHINE_INSPECT_DATA_LCR',
    'IQ_MACHINE_INSPECT_DATA_MANUAL', 'IQ_MACHINE_INSPECT_DATA_MAOI', 'IQ_MACHINE_INSPECT_DATA_MAOI_DFT',
    'IQ_MACHINE_INSPECT_DATA_MAOI_NG', 'IQ_MACHINE_INSPECT_DATA_MASK', 'IQ_MACHINE_INSPECT_DATA_MK',
    'IQ_MACHINE_INSPECT_DATA_MOUNTER_EVENT', 'IQ_MACHINE_INSPECT_DATA_M_MASK',
    'IQ_MACHINE_INSPECT_DATA_PASS', 'IQ_MACHINE_INSPECT_DATA_PBA_FT', 'IQ_MACHINE_INSPECT_DATA_PBA_FT_NG',
    'IQ_MACHINE_INSPECT_DATA_PBA_TVSET', 'IQ_MACHINE_INSPECT_DATA_PICKUP',
    'IQ_MACHINE_INSPECT_DATA_REFLOW', 'IQ_MACHINE_INSPECT_DATA_RT', 'IQ_MACHINE_INSPECT_DATA_RW',
    'IQ_MACHINE_INSPECT_DATA_SOLDER', 'IQ_MACHINE_INSPECT_DATA_SP', 'IQ_MACHINE_INSPECT_DATA_SPI',
    'IQ_MACHINE_INSPECT_DATA_SPI_DFT', 'IQ_MACHINE_INSPECT_DATA_SPI_DTL', 'IQ_MACHINE_INSPECT_DATA_SPI_DTL_LDB',
    'IQ_MACHINE_INSPECT_DATA_SPI_LDB', 'IQ_MACHINE_INSPECT_DATA_SPI_NG', 'IQ_MACHINE_INSPECT_DATA_WAVE1',
    'IQ_MACHINE_INSPECT_MANUAL', 'IQ_MACHINE_INSPECT_MNT_JOINT', 'IQ_MACHINE_INSPECT_MOUNTER_POWER',
    'IQ_MACHINE_INSPECT_NPM1_RAW', 'IQ_MACHINE_INSPECT_NPM2_RAW', 'IQ_MACHINE_INSPECT_NPM3_RAW',
    'IQ_MACHINE_INSPECT_NSNP', 'IQ_MACHINE_INSPECT_PICKUP', 'IQ_MACHINE_INSPECT_PICKUP_QRY',
    'IQ_MACHINE_INSPECT_PICKUP_RATE', 'IQ_MACHINE_INSPECT_PMNT1', 'IQ_MACHINE_INSPECT_PMNT2',
    'IQ_MACHINE_INSPECT_PMNT3', 'IQ_MACHINE_INSPECT_PMNT4', 'IQ_MACHINE_INSPECT_PMNT4_ERROR',
    'IQ_MACHINE_INSPECT_RESULT', 'IQ_MACHINE_INSPECT_SMNT1', 'IQ_MACHINE_INSPECT_SMNT2',
    'IQ_MACHINE_INSPECT_SPI', 'IQ_MACHINE_INSPECT_SPI_NG', 'IQ_MACHINE_INSPECT_SPLICING_EVENT',
    'IQ_OQC_INSPECT_HISTORY', 'IQ_OQC_REQUEST_QMS', 'IQ_OQC_REQUEST_QMS_DETAIL',
    'IQ_PRODUCT_PERFECT_QC_HISTORY', 'IQ_PRODUCT_REWORK_MASTER', 'IQ_PRODUCT_REWORK_PROCESS',
    'IQ_PRODUCT_REWORK_SERIAL', 'IQ_PRODUCT_REWORK_SERIAL_BACK', 'IQ_PRODUCT_TARGET_QC_HISTORY',
    'IQ_PRODUCT_WQC', 'IQ_SUPPLIER_LOT_BLOKING'
]

total_updated = 0
total_tables = 0
for table in tables:
    result = subprocess.run(
        ['python', 'C:/Users/hsyou/.claude/skills/oracle-db/scripts/add_code_comments.py', table, '--site', 'SVEHICLEPDB'],
        capture_output=True, text=True
    )
    try:
        data = json.loads(result.stdout)
        if data['success'] and data['updated']:
            print(f'{table}: {len(data["updated"])}개 컬럼 업데이트')
            total_updated += len(data['updated'])
            total_tables += 1
    except Exception as e:
        print(f'{table}: 오류 - {e}')

print(f'\nIQ* 테이블: {total_tables}개 테이블, 총 {total_updated}개 컬럼 업데이트 완료')
