#!/usr/bin/env python3
import subprocess
import json

# IM* 테이블 (자재/재고 관련 주요 테이블)
tables = [
    'IM_ASSY_INVENTORY_CHECK_BCD', 'IM_INVENTORY_CLOSE_SETTING', 'IM_ITEM_ARRIVAL',
    'IM_ITEM_ARRIVAL_GEN', 'IM_ITEM_ASSEMBLY_REQUIR_ORDER', 'IM_ITEM_BAD_INVENTORY',
    'IM_ITEM_BAKING_MASTER', 'IM_ITEM_BARCODE_XRAY_RETURN', 'IM_ITEM_BILL_DISBURSE',
    'IM_ITEM_CURRENT_UNIT_PRICE', 'IM_ITEM_DETAIL_4_PROFIT_COST', 'IM_ITEM_DIRECT_ORDER',
    'IM_ITEM_DIVIDE_HIST', 'IM_ITEM_EPOXY_INPUT_HIST', 'IM_ITEM_EPOXY_MASTER',
    'IM_ITEM_EXPENSE_COST_DISTRIBUT', 'IM_ITEM_FBACK_INVENTORY', 'IM_ITEM_FBACK_INVENTORY_CHECK',
    'IM_ITEM_FBACK_INVENTORY_CLOSE', 'IM_ITEM_FBACK_ISSUE', 'IM_ITEM_FBACK_RECEIPT',
    'IM_ITEM_INVENTORY', 'IM_ITEM_INVENTORY_4_TIME', 'IM_ITEM_INVENTORY_BARCODE',
    'IM_ITEM_INVENTORY_CHECK', 'IM_ITEM_INVENTORY_CHECK_BCD', 'IM_ITEM_INVENTORY_CLOSE',
    'IM_ITEM_INVENTORY_GEN', 'IM_ITEM_INVENTORY_HISTORY', 'IM_ITEM_INVENTORY_HOLD',
    'IM_ITEM_INVENTORY_LEDGER_REGEN', 'IM_ITEM_INVENTORY_MOVE_HIST', 'IM_ITEM_INVENTORY_SCAN',
    'IM_ITEM_INV_CHECK_INPUT_QTY', 'IM_ITEM_ISSUE', 'IM_ITEM_ISSUE_LEDGER_REGEN',
    'IM_ITEM_ISSUE_LOSS', 'IM_ITEM_ISSUE_RETURN_REQUEST', 'IM_ITEM_LEDGER',
    'IM_ITEM_LOCATION', 'IM_ITEM_LOCATION_MOVE_HIST', 'IM_ITEM_MANUAL_INPUT_HISTORY',
    'IM_ITEM_MASTER', 'IM_ITEM_MASTER_BACKUP', 'IM_ITEM_MASTER_PLAN_4_PO',
    'IM_ITEM_MASTER_PLAN_4_REQUIR', 'IM_ITEM_MATERIAL_SUPPLIER_BARCODE', 'IM_ITEM_MSL_CHECK_MASTER',
    'IM_ITEM_PURCHASE_ORDER', 'IM_ITEM_PURCHASE_ORDER_GEN', 'IM_ITEM_PURCHASE_ORDER_PLAN',
    'IM_ITEM_PURCHASE_ORDER_WAIT', 'IM_ITEM_PURCHASE_REQUIR_ORDER', 'IM_ITEM_RANK_MASTER',
    'IM_ITEM_RECEIPT', 'IM_ITEM_RECEIPT_4_BASE_INV', 'IM_ITEM_RECEIPT_BARCODE',
    'IM_ITEM_RECEIPT_BARCODE_LOTBK', 'IM_ITEM_RECEIPT_EXPENSE_COST', 'IM_ITEM_RECEIPT_INVOICE_MASTER',
    'IM_ITEM_RECEIPT_LEDGER_REGEN', 'IM_ITEM_RECEIPT_RETURN_REQUEST', 'IM_ITEM_RECEIPT_SLIP',
    'IM_ITEM_RECEIPT_TEMP', 'IM_ITEM_RECYCLE_INVENTORY', 'IM_ITEM_REPAIR_INVENTORY',
    'IM_ITEM_REPAIR_INVENTORY_CHECK', 'IM_ITEM_REPAIR_INVENTORY_CLOSE', 'IM_ITEM_REPAIR_ISSUE',
    'IM_ITEM_REPAIR_RECEIPT', 'IM_ITEM_REQUEST', 'IM_ITEM_REQUEST_EXCEPTION',
    'IM_ITEM_REQUEST_HISTORY', 'IM_ITEM_REQUIRMENT_LONGTERM', 'IM_ITEM_REQUIRMENT_ORDER',
    'IM_ITEM_REQUIRMENT_PLAN', 'IM_ITEM_REQUIRMENT_PLAN_TEMP', 'IM_ITEM_REQUIR_PLAN_TEMP',
    'IM_ITEM_SALE_INVENTORY', 'IM_ITEM_SALE_INVENTORY_CHECK', 'IM_ITEM_SALE_INVENTORY_CLOSE',
    'IM_ITEM_SALE_INVOICE_MASTER', 'IM_ITEM_SALE_ISSUE', 'IM_ITEM_SALE_PRICE',
    'IM_ITEM_SALE_RECEIPT', 'IM_ITEM_SCRAP_INVENTORY_CLOSE', 'IM_ITEM_SCRAP_ISSUE',
    'IM_ITEM_SCRAP_RECEIPT', 'IM_ITEM_SOLDER_INPUT_HIST', 'IM_ITEM_SOLDER_MASTER',
    'IM_ITEM_SOLDER_MASTER_HIS', 'IM_ITEM_SOLDER_TIMECHECK', 'IM_ITEM_TOTAL_4_PROFIT_COST',
    'IM_ITEM_TOTAL_COST', 'IM_ITEM_TOTAL_INVENTORY', 'IM_ITEM_TOTAL_INVENTORY_CLOSE',
    'IM_ITEM_TOTAL_INVENTORY_EXP', 'IM_ITEM_TOTAL_INVENTORY_GEN', 'IM_ITEM_UNIT_PRICE',
    'IM_ITEM_UNIT_PRICE_BACK', 'IM_ITEM_WEEK', 'IM_ITEM_WORKSTAGE_INVENTORY',
    'IM_ITEM_WORKSTAGE_INV_CHECK', 'IM_ITEM_WORKSTAGE_INV_CLOSE', 'IM_ITEM_WORKSTAGE_INV_EXPAND',
    'IM_ITEM_WORKSTAGE_ISSUE', 'IM_ITEM_WORKSTAGE_ISSUE_GEN', 'IM_ITEM_WORKSTAGE_ISSUE_PLAN',
    'IM_ITEM_WORKSTAGE_RECEIPT', 'IM_ITEM_WORK_ORDER', 'IM_ITEM_WS_INVENTORY_REVERSE',
    'IM_ITEM_WS_INVENTORY_REV_NOUSE', 'IM_ITEM_WS_INVE_CHECK_EXCEL', 'IM_ITEM_WS_RECEIPT_4_BASE_INV',
    'IM_MATERIAL_REEL_IMAGE', 'IM_MATERIAL_REQUEST', 'IM_TOTAL_PAYABLE_MASTER'
]

total_updated = 0
total_tables = 0
for table in tables:
    result = subprocess.run(
        ['python', 'C:/Users/hsyou/.claude/skills/oracle-db/scripts/add_code_comments.py', table, '--site', 'SVEHICLEPDB'],
        capture_output=True, text=True
    )
    try:
        data = json.loads(result.stdout)
        if data['success'] and data['updated']:
            print(f'{table}: {len(data["updated"])}개 컬럼 업데이트')
            total_updated += len(data['updated'])
            total_tables += 1
    except Exception as e:
        print(f'{table}: 오류 - {e}')

print(f'\nIM* 테이블: {total_tables}개 테이블, 총 {total_updated}개 컬럼 업데이트 완료')
